// <auto-generated />

// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "<Pending>", Scope = "member", Target = "~M:Northwind.Context.MsSql.Commands.QuarterlyOrdersCommand.RunCommand(Microsoft.Data.SqlClient.SqlCommand)~System.Threading.Tasks.Task{System.Collections.Generic.IList{Northwind.Context.Models.QuarterlyOrder}}")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1128:Put constructor initializers on their own line", Justification = "<Pending>", Scope = "member", Target = "~M:Northwind.Context.MsSql.Commands.QuarterlyOrdersCommand.#ctor(System.String)")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "<Pending>", Scope = "member", Target = "~M:Northwind.Context.MsSql.Commands.SalesByCategoryReportCommand.RunCommand(Microsoft.Data.SqlClient.SqlCommand)~System.Threading.Tasks.Task{System.Collections.Generic.IList{Northwind.Context.Models.SalesByCategory}}")]
